export const SELECT_FOLDER = "SELECT_FOLDER";
export const UPDATE_FOLDER = "UPDATE_FOLDER";
export const SET_CHILD_FOLDERS = "SET_CHILD_FOLDERS";
export const SET_CHILD_FILES = "SET_CHILD_FILES";
